# Generated by Django 4.2.3 on 2023-07-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('number_of_levels', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('area', models.PositiveSmallIntegerField(default=200)),
                ('nunber_of_people', models.PositiveSmallIntegerField(default=60)),
                ('more_info', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
