# Generated by Django 4.2.2 on 2023-07-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
