# Generated by Django 4.2.2 on 2023-07-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0002_local_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDescribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
