# Generated by Django 4.2.2 on 2023-07-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0003_shortdescribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('add', models.ManyToManyField(to='gramofonsite.local')),
            ],
        ),
    ]
