# Generated by Django 4.2.2 on 2023-07-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0004_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='describe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gramofonsite.shortdescribe'),
        ),
    ]
