# Generated by Django 4.2.2 on 2023-07-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0005_local_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='describe',
        ),
        migrations.AddField(
            model_name='local',
            name='street',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='title_page',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='ShortDescribe',
        ),
    ]
