# Generated by Django 4.2.2 on 2023-07-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0006_remove_local_describe_local_street_local_title_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image')),
                ('discrabe', models.TextField(blank=True, default='', null=True)),
                ('add', models.ManyToManyField(to='gramofonsite.local')),
            ],
        ),
    ]
