# Generated by Django 4.2.2 on 2023-07-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0007_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
