# Generated by Django 4.2.2 on 2023-07-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0008_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDescribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='describe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gramofonsite.shortdescribe'),
        ),
    ]
