# Generated by Django 4.2.2 on 2023-07-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0011_room_alter_local_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='describe',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='describe',
            new_name='description',
        ),
    ]
