# Generated by Django 4.2.2 on 2023-07-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0012_remove_local_describe_local_note_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('Dance', 'Sala Taneczna'), ('WC', 'Toaleta'), ('Cook', 'Kuchnia')], default='Dance', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gramofonsite.local')),
            ],
        ),
    ]
