# Generated by Django 4.2.2 on 2023-07-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0013_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='image',
            new_name='image_base',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='title',
            new_name='title_local',
        ),
        migrations.RemoveField(
            model_name='local',
            name='note',
        ),
        migrations.AddField(
            model_name='local',
            name='morska_dance_room',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='morska_img_dance',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='local',
            name='morska_img_toilet',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='local',
            name='morska_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='morska_toilet',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='ShortDescribe',
        ),
    ]
