# Generated by Django 4.2.2 on 2023-07-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0014_rename_image_local_image_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='morska_title',
            new_name='dance_room_title',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='morska_img_dance',
            new_name='img_dance_room',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='morska_img_toilet',
            new_name='img_ktchen',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='morska_dance_room',
            new_name='note_dance_room',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='morska_toilet',
            new_name='note_kitchen',
        ),
        migrations.AddField(
            model_name='local',
            name='img_toilet',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='local',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='local',
            name='note_toilet',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='more_info',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
