# Generated by Django 4.2.2 on 2023-07-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0015_rename_morska_title_local_dance_room_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='kitchen_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='toilet_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='dance_room_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='note_dance_room',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='note_kitchen',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='note_toilet',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
