# Generated by Django 4.2.3 on 2023-07-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0016_local_kitchen_title_local_toilet_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='local',
            name='area',
        ),
        migrations.RemoveField(
            model_name='local',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='local',
            name='more_info',
        ),
        migrations.RemoveField(
            model_name='local',
            name='number_of_levels',
        ),
        migrations.RemoveField(
            model_name='local',
            name='nunber_of_people',
        ),
        migrations.AddField(
            model_name='local',
            name='local_note',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='short_note',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
