# Generated by Django 4.2.3 on 2023-07-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0017_headpage_remove_local_area_remove_local_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='local_note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='short_note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
