# Generated by Django 4.2.3 on 2023-07-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0018_alter_local_local_note_alter_local_short_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headpage',
            old_name='background_image',
            new_name='image_background',
        ),
        migrations.RenameField(
            model_name='headpage',
            old_name='logo_image',
            new_name='image_logo',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='img_dance_room',
            new_name='dance_room_img',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='note_dance_room',
            new_name='dance_room_note',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='note_kitchen',
            new_name='kitchen_note',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='img_ktchen',
            new_name='ktchen_img',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='local_note',
            new_name='note_local',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='short_note',
            new_name='note_short',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='img_toilet',
            new_name='toilet_img',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='note_toilet',
            new_name='toilet_note',
        ),
    ]
