# Generated by Django 4.2.3 on 2023-07-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0019_rename_background_image_headpage_image_background_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='ktchen_img',
            new_name='kitchen_img',
        ),
    ]
