# Generated by Django 4.2.3 on 2023-07-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0020_rename_ktchen_img_local_kitchen_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='banquet_hall_img',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='local',
            name='banquet_hall_note',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='banquet_hall_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='equipment_img',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='local',
            name='equipment_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='equipment_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
