# Generated by Django 4.2.3 on 2023-07-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0021_local_banquet_hall_img_local_banquet_hall_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='banquet_hall_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='equipment_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
