# Generated by Django 4.2.2 on 2023-07-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0022_alter_local_banquet_hall_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='title_local',
            field=models.CharField(max_length=20, verbose_name='Nazwa lokalu'),
        ),
    ]
