# Generated by Django 4.2.2 on 2023-08-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0024_advantages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='special_features',
            field=models.CharField(max_length=200, null=True, verbose_name='Cechy szczególne - wypunktowanie'),
        ),
    ]
