# Generated by Django 4.2.2 on 2023-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramofonsite', '0025_alter_advantages_special_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='special_features',
            field=models.CharField(default='zalety', max_length=200, verbose_name='Cechy szczególne - wypunktowanie'),
        ),
    ]
